version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: healthtrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-healthtrack_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-healthtrack_password}
      POSTGRES_DB: ${DB_NAME:-healthtrack}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
